name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]  # Triggers on PR open and commits to PR

jobs:
  ci:
    uses: maris-test/reusable-workflows/.github/workflows/ci-workflow.yml@main
    with:
      run-translations: true
      run-build: true
      run-tests: false
